### ISSUE TITLE
Usage of let else statement in `na-winit-wgpu` (and possible elsewhere) could eliminate unnecessary nesting

### ISSUE THREAD

**Issue by JohnScience** [rust-mobile/rust-android-examples#13]
As I was assessing the maturity of Rust for mobile development, I tried different things.

I used `na-winit-wgpu` example as a template for <https://github.com/JohnScience/winit_wgpu_android_native_activity>.

While I was working on it, I noticed that you could make the code less nested with these stable features:

* [`let-else`](https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html).
* [labelled blocks](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#break-from-labeled-blocks).

P.S.

Only after reading my message I realized that it would likely come across as being negative. You did an amazing job. I rewrote the title to make it more positive.

**Comment by MarijnS95** [comment]
If you're assessing the maturity of the ecosystem by looking at examples and considering backwards compatibility with older (>6 months) Rust a bad thing, you're ~in the wrong place~ evaluating the wrong thing.
