### ISSUE TITLE
agdk-eframe panics on resume if modified to use glow backend

### ISSUE THREAD

**Issue by tkkcc** [rust-mobile/rust-android-examples#6]
agdk-eframe ui state lose or quit when bring app to foreground from background.

using eframe 0.22 and winit 0.28, the error is
```txt
thread '<unnamed>' panicked at 'winit window doesn't exist'
```

eframe has an [on_resume]( 
https://github.com/emilk/egui/blob/073f49682da20828dbd118f1d97e14a2b3879631/crates/eframe/src/native/run.rs#L519) handler, but it's not called.

**Comment by tkkcc** [comment]
it's only happen with glow backend, default wgpu backend is fine.

**Comment by rib** [comment]
Hey @tkkcc, should we close this since your egui PR was merged? https://github.com/emilk/egui/pull/3080
